pipeline {
  agent any
  stages {
      stage('run angular image') {
        steps {
          git branch: 'main', credentialsId: 'Git', url: 'https://github.com/georgos987/tools.shop.GCP.git'
          withCredentials([file(credentialsId: 'gcloud', variable: 'GCLOID_LOGIN')]) {
           bat 'gcloud auth activate-service-account --key-file=%GCLOID_LOGIN%'
          }
          withCredentials([usernamePassword( credentialsId: 'docker-hub', usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD')]) {
           bat 'docker login -u  %USERNAME%  -p %PASSWORD%'
          }
          bat 'docker rmi -f georgos987/angularimage'
          bat 'cd frontend & docker build -t  angularimage .'
          bat 'docker tag angularimage  georgos987/angularimage'
          bat 'docker push  georgos987/angularimage'
          bat 'cd kubernetes/GCP & kubectl apply -f ./angular-GCP.yml'
        }
      }
  }
}

