apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app-spring
  name: app-spring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-spring
  strategy: {}
  template:
    metadata:
      labels:
        app: app-spring
    spec:
      containers:
      - image: georgos987/springimage
        name: app-spring
        volumeMounts:
          - mountPath: /workspace/BOOT-INF/classes/application.properties
            subPath: application.properties
            name: application-properties
        resources: {}
      volumes:
        - name: application-properties
          configMap:
            name: application-properties-config
            items:
             - key: application.properties
               path: application.properties
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: spring-service
  name: spring-service
spec:
  type: LoadBalancer
  loadBalancerIP: 35.246.87.127
  ports:
  - name: 8080-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: app-spring

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: application-properties-config
data:
  
  application.properties: |
    # Georogs
    spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
    spring.datasource.url=jdbc:mysql://mysql-service-tool:3306/tools_shop?useSSL=false&useUnicode=yes&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&serverTimezone=UTC
    spring.datasource.username=georgos
    spring.datasource.password=12122012ge
    spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQL8Dialect
    spring.jpa.hibernate.ddl-auto = update
    logging.level.org.hibernate.SQL= DEBUG
    spring.datasource.initialization-mode=always
    spring.jackson.serialization.WRITE_DATES_AS_TIMESTAMPS= false
    spring.jackson.time-zone= UTC
    app.jwtSecret= JWTSuperSecretKey
    app.jwtExpirationInMs = 604800000
