apiVersion: v1
kind: Service
metadata:
  name: jenkins
spec:
  type: LoadBalancer 
  ports:
    - port: 8088
      targetPort: 8080
      nodePort: 30001
  selector:
    app: jenkins
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-jnlp
spec:
  type: ClusterIP
  ports:
    - port: 50000
      targetPort: 50000
  selector:
    app: jenkins
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-local
spec:
  type: LoadBalancer
  ports:
    - port: 8081
      targetPort: 8081
  selector:
    app: jenkins 
     